## Today Concepts:
```
1.List Comprehension
2.Dict Comprehension
3.Set Comprehension

Packages
1.Numpy
2.Pandas
3.Matplotlib
    Machine Learning
    AI
    Data Analytics
    Deep Learning
4.Seaborn
5.Scikit learn

Numpy --> Package
```

In [2]:
# List Comprehension

List1 = [5,10,15,20,25,30]

In [5]:
# Basic Procedure
output=[]
for value in List1:
    op=value**2
    # print(op)
    output.append(op)
print(output)

[25, 100, 225, 400, 625, 900]


### List Com
```
Syntax:

[output_statement for variable in "Iterable" "conditions"]

```

In [6]:
[value**2  for value in List1]

[25, 100, 225, 400, 625, 900]

In [8]:
[(2,'*',i,"=",2*i)   for i in range(1,11)]

[(2, '*', 1, '=', 2),
 (2, '*', 2, '=', 4),
 (2, '*', 3, '=', 6),
 (2, '*', 4, '=', 8),
 (2, '*', 5, '=', 10),
 (2, '*', 6, '=', 12),
 (2, '*', 7, '=', 14),
 (2, '*', 8, '=', 16),
 (2, '*', 9, '=', 18),
 (2, '*', 10, '=', 20)]

In [10]:
# Example 3

s = "apssdc@147"
[char for char in s if char.isalpha()]

['a', 'p', 's', 's', 'd', 'c']

In [11]:
# Example 4
[year for year in range(2000,2021) if year%4==0 and year%100!=0 or year%400 == 0]

[2000, 2004, 2008, 2012, 2016, 2020]

# dict Comprehension
```
syntax
{key:value loop condition}
```

In [12]:
name = "rajakumar"

{char:name.count(char) for char in name}

{'r': 2, 'a': 3, 'j': 1, 'k': 1, 'u': 1, 'm': 1}

In [13]:
[name.count(char) for char in name]

[2, 3, 1, 3, 1, 1, 1, 3, 2]

In [16]:
word = "I am siva have been working in apssdc"
[string   for string in word.split(" ") if len(string)==4]

['siva', 'have', 'been']

```
task
output:
    
    {string:length,............}
```

In [17]:
statement = "lakshmi is a good girl"
{string:statement.count(string) for string in statement.split()}

{'lakshmi': 1, 'is': 1, 'a': 2, 'good': 1, 'girl': 1}

In [18]:
statement = "lakshmi is a good girl"

{string:len(string) for string in statement.split(" ")}

{'lakshmi': 7, 'is': 2, 'a': 1, 'good': 4, 'girl': 4}

In [ ]:
# Set Comprehension

{output_statement loop  condition}

In [19]:
#Example

num = [1,2,3,4,5,6,1,2,3]

{each for each in num}



{1, 2, 3, 4, 5, 6}

In [20]:
# Exampl2

p="apssdc"

{char*2 for char in p}

{'aa', 'cc', 'dd', 'pp', 'ss'}

# Numpy

```
--> Numerical Python
--> Numpy is one of the package 
--> Module is a .py file, in that file we have different functions 
--> Package is a collection of modules
```

## Numpy Declaration and importing
```
Declaration:
1.import numpy 
2.import numpy as short_var_name

types of data:
1. 1-D Array
2. 2-D Array
3. 3-D Array
```



In [21]:
import numpy

In [22]:
numpy.array([1,2,3,4])

array([1, 2, 3, 4])

```
Advantages:
-----------
1.For solving Numerical Operation in simple 
2.Operations are simple compare to basic
3.It's takes less time compare to basic procedures
```

In [25]:
list1 = [1,3,5,7,9]
list2 = [2,4,6,8,10]
#(lambda x,y:x*y,list1,list2)
list(map(lambda x,y:x*y,list1,list2))

[2, 12, 30, 56, 90]

In [31]:
# Basic Procedure
list1 = [1,3,5,7,9]
list2 = [2,4,6,8,10]
#(lambda x,y:x*y,list1,list2)
print(list(map(lambda x,y:x*y,list1,list2)))

print("---------------------------------------")

arr1 = numpy.array(list1)
arr2 = numpy.array(list2)
print(arr1,arr1.dtype)
print(arr2,arr2.dtype)

[2, 12, 30, 56, 90]
---------------------------------------
[1 3 5 7 9] int32
[ 2  4  6  8 10] int32


In [28]:
arr1.ndim

1

In [29]:
arr2.ndim

1

In [30]:
arr1*arr2

array([ 2, 12, 30, 56, 90])

In [33]:
for i in range(1,10,5):
    print(i)

1
6


In [34]:
import numpy as np

In [35]:
np.arange(1,5,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [36]:
# 2-D Array

np.array([1,2,3])

array([1, 2, 3])

In [37]:
np.array([[1,3,4],[4,8,5]])

array([[1, 3, 4],
       [4, 8, 5]])

In [38]:
h = np.arange(1,13,1)
h

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [40]:
h.ndim
h.shape

(12,)

In [42]:
# reshape
# converting 1-D Ayyay to either 2-D or 3-D

m=h.reshape(4,3)
m
# it converts into 4 rows 3 columns

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [43]:
m[0,0]

1

In [44]:
m[0]

array([1, 2, 3])

In [45]:
m[0][0]

1

In [46]:
m[0]

array([1, 2, 3])

In [47]:
m[0,:]

array([1, 2, 3])

In [48]:
m[1]

array([4, 5, 6])

In [49]:
m

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [50]:
m[:,0]

array([ 1,  4,  7, 10])

In [51]:
m[:,1]

array([ 2,  5,  8, 11])

In [55]:
thd=np.arange(1,13).reshape(2,2,3)
thd

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [57]:
b = np.array([[[2,3],
              [4,5]],
            [[7,10],
             [9,11]]])

# [[[1,2],[3,4]],[[7,8],[9,10]]]

In [58]:
b

array([[[ 2,  3],
        [ 4,  5]],

       [[ 7, 10],
        [ 9, 11]]])

In [59]:
b[0]

array([[2, 3],
       [4, 5]])

In [60]:
b[0][1]

array([4, 5])

In [62]:
b[0][1][0]

4

In [63]:
b[1,0,1]

10

In [66]:
# b["part","row_num","col_num"]

stds = np.array([[45,83,67,47],[32,41,49,62],[97,80,79,92]])

stds

array([[45, 83, 67, 47],
       [32, 41, 49, 62],
       [97, 80, 79, 92]])

In [67]:
stds[1,2]

49

In [68]:
stds[2,2]=97

In [69]:
stds

array([[45, 83, 67, 47],
       [32, 41, 49, 62],
       [97, 80, 97, 92]])

In [74]:
# ones
k= np.ones(5)
k

array([1., 1., 1., 1., 1.])

In [75]:
k.dtype

dtype('float64')

In [76]:
y= np.ones(5,dtype=int)
y

array([1, 1, 1, 1, 1])

In [77]:
# zeros
t=np.zeros(100)
t

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [78]:
t.dtype

dtype('float64')

In [79]:
t=np.zeros(100,dtype=int)
t

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [80]:
t.dtype

dtype('int32')

In [82]:
# identity Matrix
n = np.eye(4,4,dtype = int)
n

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [84]:
np.diag(n)

array([1, 1, 1, 1])

In [85]:
np.sin(90)

0.8939966636005579

In [88]:
np.sin(0)

0.0

In [90]:
np.sin(180)

-0.8011526357338304

In [91]:
np.cos(0)

1.0

In [92]:
np.sinh(10)

11013.232874703393

In [96]:
np.sinh(90)

6.102016471589204e+38

In [97]:
np.sin(90)

0.8939966636005579

In [100]:
np.sin(np.deg2rad(90))

1.0

lambda:
-----------
--> this is the special function in python
--> Function declaration we need function_name but lambda not takes name


In [101]:
lambda x:x**3,[1,2,3,4,5]

(<function __main__.<lambda>(x)>, [1, 2, 3, 4, 5])

In [103]:
list((lambda x:x**3,[1,2,3,4,5]))

[<function __main__.<lambda>(x)>, [1, 2, 3, 4, 5]]

In [104]:
1.1**3 -->3 --> map -->list[3,8,.....]

SyntaxError: invalid syntax (<ipython-input-104-bdd344e123ac>, line 1)

In [105]:
list(map(lambda x:x**3,[1,2,3,4,5]))

[1, 8, 27, 64, 125]