# Good Morning to All
```
Numpy
 --> Declaration of data
     --> 1-D Array
     --> 2-D Array
     --> 3-D Array
 --> Methods
     --> arange
     --> ones
     --> zeros
     --> eye

Today Agenda:
-------------
--> Numpy All Concept
--> Pandas
```

     

In [1]:
lambda x,y:x*y,5,10

(<function __main__.<lambda>(x, y)>, 5, 10)

In [2]:
list(map(lambda x,y:x*y,5,10))

TypeError: 'int' object is not iterable

In [3]:
list(map(lambda x,y:x*y,[5],[10]))

[50]

In [4]:
# Numpy
## Single Dimension Array
import numpy as n
sd = n.array([1,8,5,6])
sd

array([1, 8, 5, 6])

In [5]:
# 2-D Array
td=n.array([[1,2,3],[7,8,9]])
td

array([[1, 2, 3],
       [7, 8, 9]])

In [7]:
# 3-D Array
b= n.array([[[2,3],
              [4,5]], 
            [[7,10],
             [9,11]]])
b

array([[[ 2,  3],
        [ 4,  5]],

       [[ 7, 10],
        [ 9, 11]]])

In [10]:
# random
n.random.randint(5,10,[3,3])

array([[7, 7, 7],
       [8, 5, 6],
       [5, 9, 7]])

In [11]:
n.random.random([5,10])

array([[0.77225062, 0.98791799, 0.78068155, 0.18556007, 0.93034056,
        0.36561554, 0.91573923, 0.71819089, 0.29417405, 0.71574226],
       [0.44419505, 0.13747617, 0.57570006, 0.06705333, 0.90536103,
        0.05372298, 0.58165664, 0.57053674, 0.67728795, 0.88939529],
       [0.39048068, 0.95372783, 0.23318083, 0.25525672, 0.54189693,
        0.77353369, 0.74566609, 0.30167473, 0.38217006, 0.74476871],
       [0.03039599, 0.84869925, 0.67880134, 0.37339259, 0.6398859 ,
        0.77130207, 0.98506556, 0.83607423, 0.37157832, 0.20747588],
       [0.21017513, 0.86970843, 0.08780522, 0.65393172, 0.235402  ,
        0.14594079, 0.16577264, 0.1975159 , 0.71674194, 0.67491959]])

In [12]:
n.random.randint(25,30,[1,10])

array([[26, 28, 26, 28, 27, 25, 25, 25, 27, 27]])

In [15]:
# tile
n.tile([1,2],[2,5])

array([[1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2]])

In [16]:
n.full([5,6],10)

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [17]:
n.full([10,10],1000)

array([[1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000]])

In [18]:
# linspace
n.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [19]:
n.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [20]:
(1+10)/20

0.55

In [21]:
(10-1)/20

0.45

In [22]:
n.tile(10,[5,6])

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [23]:
n.full([5,6],10)

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [24]:
n.tile([4,5],[3,3])

array([[4, 5, 4, 5, 4, 5],
       [4, 5, 4, 5, 4, 5],
       [4, 5, 4, 5, 4, 5]])

In [25]:
n.full([3,3],[5,6])

ValueError: could not broadcast input array from shape (2) into shape (3,3)

In [26]:
na = n.random.randint(1,10,[5,5])
na

array([[4, 8, 9, 3, 3],
       [9, 3, 1, 4, 5],
       [8, 6, 5, 7, 1],
       [4, 7, 6, 6, 7],
       [1, 1, 3, 3, 4]])

In [27]:
na.shape

(5, 5)

In [28]:
na.ndim

2

In [29]:
na.dtype

dtype('int32')

In [34]:
na.itemsize

4

In [35]:
na

array([[4, 8, 9, 3, 3],
       [9, 3, 1, 4, 5],
       [8, 6, 5, 7, 1],
       [4, 7, 6, 6, 7],
       [1, 1, 3, 3, 4]])

In [36]:
n.sin(60)

-0.3048106211022167

In [37]:
n.exp(10)

22026.465794806718

In [38]:
n.sqrt(144)

12.0

In [1]:
list1 = [i for i in range(10000000)]
list2 = [i*10 for i in range(10000000)]

import time

start_time = time.time()
k= list(map(lambda x,y:x*y,list1,list2))
end_time = time.time()

final_time = end_time-start_time
print("Time taken by general procedure",final_time)

Time taken by general procedure 3.2468276023864746


In [2]:
import numpy as ns
r1=ns.array(list1)
r2=ns.array(list2)

st_time = time.time()
k= r1*r2
ed_time=time.time()

out_time=ed_time-st_time
print("Numpy time taken ",out_time)

Numpy time taken  0.06534004211425781
